### PR TITLE
fix product page bug

### LINKED ISSUE #74: Product page bug
There is a bug with product page. The user can only go to the item page from product page (e.g. For-him, For her, etc.) by clicking on the photo, they should also be able to go to the page by clicking on the title and subtitles

### PR DESCRIPTION
**Pull request by flying-cmd**
Use event delegation to place the function that jumps to a single product page on the entire div (the div including img, title and subtitle).

### CODE REVIEW

File: frontend/components/common/IndividualProduct.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ export function IndividualProductForShoppingPage({
     <div 
       className="grid grid-rows-[repeat(4,auto)] items-center justify-center group gap-1 md:gap-2 2xl:gap-4 cursor-pointer text-center"
       data-id={id}
-      onClick={(e) => clickHandler(e)}
+      onClick={clickHandler}
```
Comment (flying-cmd) [inline frontend/components/common/IndividualProduct.tsx]: I found that React automatically passes the event object, so I changed the arrow function to the function name.

**Comment by RuntaoZhuge** [comment]
Can you please fix the conflicts. I pushed some changes to the product

**Comment by RuntaoZhuge** [comment]
Can you address this comment?
Improvement: Refactor the clickHandler logic into a shared utility function to reduce code duplication.
